Update DG for comment command
AY2223S1-CS2103T-T15-3/tp pull request #158
Opened 2022-10-22 07:01 UTC by marcuslowhuiyu

Fixed spelling error in adding tutor description too

2022-10-22 18:08 UTC, t1mzzz requested changes
LGTM, but make the small modification first.

2022-10-22 18:08 UTC, t1mzzz commented on docs/DeveloperGuide.md
> +![SortSequenceDiagram](./images/CommentSequenceDiagram.png)
Make sure to change the alternative text to `CommentSequenceDiagram`.

2022-10-25 02:28 UTC, leirdas approved these changes
LGTM

2022-10-25 02:34 UTC, t1mzzz approved these changes

2022-10-25 02:34 UTC, merged